### PR TITLE
#56: rustdoc: module definitions

### LINKED ISSUE #56: doc: Module Level Documentation
We need some basic module level docs for all our modules.

### PR DESCRIPTION
**Pull request by wthrajat**
Aims to fix #56.

### CODE REVIEW

**Review by rajarshimaitra — COMMENTED** [review]
Concept ACK.

Thanks for taking this up. Good going. 

I will also keep pushing my modification and changes here in this PR. As we will be just writing english, doesn't require a lot of reviews. But there's a bunch of typing that will go in this one.

What to do: 
- Complete rest of the module docs for each modules.
- Check `cargo doc` in your local to see how our rust doc looks like. It looks very shabby now. Keeping an eye on the auto built doc, while writing docs would help you see how different docs across the code are shown in the web format differently. run `cargo doc --open`. 
- We would wanna achieve doc standards towards rust-bitcoin. This is how their docs looks like https://docs.rs/bitcoin/latest/bitcoin/.

On my plate:
 - I will put touches on the docs that you have already put and push here, instead of making review comments.
 - As you finish the other modules, I will take them up. 
 
We will need another round of PR for all the API docs.

**Comment by wthrajat** [comment]
Added definitions for all modules described here.
```console
src/
├─ bin/
├─ maker/
├─ market/
├─ protocol/
├─ scripts/
├─ taker/
├─ wallet/
├─ watchtower/
```
Also, now frequently checking `rust doc` and actively comparing the docs with `rust-bitcoin` library.
Some modules remaining.

**Comment by rajarshimaitra** [comment]
Added some fixes and more docs. It seems good from my side. Whenever you are done with your further edits @wthrajat we can merge this.

**Review by wthrajat — COMMENTED** [review]
ACK 4b4d2af9cc80fb751b279ccbe86558ded8d4eab1. If further scope of improvement is found in module docs, it can be addressed in #57  

Also: `"Pull request authors can’t approve their own pull request"`.
Hence just commenting.

**Pull request merged**
