### PR TITLE
 remove `DisplayAddressType` struct & its implementation

### LINKED ISSUE #150: `SoB/BDKWallet`: Remove `DisplayAddressType` struct and its impl
Part of #142

### PR DESCRIPTION
**Pull request by 15IITian**
* As they are not used anywhere

Fix #150

### CODE REVIEW

**Comment by Shourya742** [comment]
@15IITian A better approach would be to avoid altering the existing wallet infrastructure and instead create a separate BDK module to accomplish the task.

**Comment by rajarshimaitra** [comment]
This specific refactor is valid, but this PR will be merged on the bdk branch, so there won't be any effect of this on master. As bit-aloo said, better not to delete anything in the bdk project and only add new files.

I actually have this refactor in my upcoming Maker app PR. So better to just skip it for bdk project.

Also make sure to run cargo fmt before pushing.

**Comment by 15IITian** [comment]
>I actually have this refactor in my upcoming Maker app PR. So better to just skip it for bdk project.

So should I close it or can it be used in `master` branch ?

**Comment by Shourya742** [comment]
@15IITian You can close this

**Pull request closed without merging**
